### ISSUE TITLE
[Supporters] - QA - Gui

### ISSUE THREAD

**Issue by Comekta** [dev-vcnafacul/frontend-v4#18]
- [x] Adicionar cursor pointer nos ícones de empresas e direcionar para o site da empresa (nesse caso é só adicionar a variável de link dentro do objeto utilizado para o carrousel).
- [x] Adicionar cursor pointer no botão de conhecer o time e um href vazio para uso futuro.
- [x] Font-size de empresas e voluntários está maior no desk (24px), correto: 20px.
- [x] Margin bottom de subtítulo está menor no desk (59px), correto: 67px.
- [x] Line-height de título dos itens de voluntários está menor do que deveria, um line height de 1,6rem já deve resolver em todas as telas.
- [x] Diminuir o margin-top do display de navegação no desk de 50px para 40px.
- [x] Diminuir o margin-top do display de navegação no desk de 82px para 72px.
- [x] O fim da seção no mobile está amior do que deveria somando 60px com mais a distancia padrão do resto do componente, se diminuir o margin-bottom pra 10px fica legal.
- [ ] A parte de empresas, seria legal pelo menos diminuir o tamanho do logo da empresa, mas pra mim é meio indiferente se estão em uma div um em cima do outro ou como estão agora.

**Comment by vhymathias** [comment]
Valeu pelo QA, Gui!

**A parte de empresas, seria legal pelo menos diminuir o tamanho do logo da empresa, mas pra mim é meio indiferente se estão em uma div um em cima do outro ou como estão agora.**
Nesse ponto eu fiquei meio perdido, você diz diminuir em altura ou comprimento?
