### ISSUE TITLE
[Platform-Section] - QA - Gui

### ISSUE THREAD

**Issue by Comekta** [dev-vcnafacul/frontend-v4#6]
- [ ] A section não está cobrindo a view width inteira, adicionar um "width: 100%" já resolve esse problema nela.
- [ ] Adicionar um cursor nos itens de navegação (cursor: pointer).
- [ ] Remover "font-family: montserrat" do texto inferior ao título.
- [ ] Remover "font-family: montserrat" do texto inferior a imagem.
- [ ] No mobile ficou faltando colocar um "font-weight: 700" quando selecionado o item de navegação
- [ ] No mobile, faltou adicionar a seta indicativa do dropdown. Esperado: 
![image](https://user-images.githubusercontent.com/54742687/102831771-55b0bc00-43cb-11eb-95f0-83b86c6dbf59.png)

- [ ] Não saquei se essa tela de notebook do mockup, seria pra alterar as imagens dentro dela, ou a imagem como um todo, caso seja o primeiro caso, teria que enquadrar as imagens dos tópicos selecionados dentro do notebook, mas é melhor confirmar com as designers.

Obs: Você pode adicionar transitions nos botões para suavizar suas seleções também, mas fica a seu critério.

**Comment by vhymathias** [comment]
Valeu pelo QA, mano!

* [ ]  A section não está cobrindo a view width inteira, adicionar um "width: 100%" já resolve esse problema nela.
**Eu não sei se o fundo cinza vai ser na largura toda ou tipo uma caixinha, vou confirmar lá no trello com as designers**
* [x]  Adicionar um cursor nos itens de navegação (cursor: pointer).
**Boa! Mobile não precisa né?**
* [ ]  Remover "font-family: montserrat" do texto inferior ao título.
**Então, pelo mockup é para ser montserrat, vou confirmar no trello**
* [ ]  Remover "font-family: montserrat" do texto inferior a imagem.
**Então, pelo mockup é para ser montserrat, vou confirmar no trello**
* [x]  No mobile ficou faltando colocar um "font-weight: 700" quando selecionado o item de navegação
**Boa!**
* [ ]  No mobile, faltou adicionar a seta indicativa do dropdown. Esperado:
  ![image](https://user-images.githubusercontent.com/54742687/102831771-55b0bc00-43cb-11eb-95f0-83b86c6dbf59.png)
**Nossa, esqueci total de perguntar isso. @lzcee Lê, vamos usar o font-awesome? Podemos adicionar como dependência no packages.json? Ou tem jeito de pegar o ícone pelo XD?**
* [ ]  Não saquei se essa tela de notebook do mockup, seria pra alterar as imagens dentro dela, ou a imagem como um todo, caso seja o primeiro caso, teria que enquadrar as imagens dos tópicos selecionados dentro do notebook, mas é melhor confirmar com as designers.
**Boa, vou perguntar**

Obs: Você pode adicionar transitions nos botões para suavizar suas seleções também, mas fica a seu critério.
**Nossa, fez muita diferença, ficou bem legal!**

**Comment by vhymathias** [comment]
PS: Para os transitions de div que aparece/desaparece, eu usei esse macete
https://velhobit.com.br/tutoriais/css-como-usar-transition-com-displayblock.html
Tem problema? Tem alguma desvantagem?

**Comment by Comekta** [comment]
Acho tranquilo usar esse macete, mas você também consegue utilizar direto props do react pra tratar suas classes também, mas não sei qual seria a prioridade de uso nesse caso...
